#spring:
#  application:
#    name: demo-feign
#  profiles:
#    active: dev
#  cloud:
#    consul: #Consul服务注册发现配置
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}
#        instance-id: ${spring.application.name}:${server.port}
#        heartbeat:
#          enabled: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus
#  metrics:
#    tags:
#      application: ${spring.application.name}
#
#server:
#  port: 9003