#spring:
#  application:
#    name: demo-gateway
#  profiles:
#    active: dev
#  cloud:
#    gateway:
#      routes:
#        - id: demo
#          uri: lb://demo
#          predicates:
#            - Path=/demo/**
#          filters:
#            - StripPrefix=1
#        - id: demo-consumer
#          uri: lb://demo-consumer
#          predicates:
#            - Path=/demo-consumer/**
#          filters:
#            - StripPrefix=1
#        - id: demo-producer
#          uri: lb://demo-producer
#          predicates:
#            - Path=/demo-producer/**
#          filters:
#            - StripPrefix=1
#    consul: #Consul服务注册发现配置
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}
#        instance-id: ${spring.application.name}:${server.port}
#        heartbeat:
#          enabled: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus
#  metrics:
#    tags:
#      application: ${spring.application.name}
#
#server:
#  port: 8000
