#spring:
#  application:
#    name: demo-producer
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://rm-m5e0e1v2346pf0u04mo.mysql.rds.aliyuncs.com:3306/crawler_info
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: gs_db
#    password: Aa123456
#  jpa:
#    hibernate:
#      ddl-autp: create-drop
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#  cloud:
#    consul: #Consul服务注册发现配置
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}
#        instance-id: ${spring.application.name}:${server.port}
#        heartbeat:
#          enabled: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus
#  metrics:
#    tags:
#      application: ${spring.application.name}
#
#server:
#  port: 9002